### PR TITLE
remote site settings helper page

### PR DESCRIPTION
**Pull request by wes1278**
Thought this might help for anyone looking to do an automatic creation of a remote site setting for sfdc to sfdc communication.

### CODE REVIEW

**Comment by afawcett** [comment]
Fantastic contribution, thank you! Could you update the README with a section describing the component and maybe a screenshot of it in action?

**Comment by wes1278** [comment]
Want to take a quick look now @afawcett ?

**Comment by afawcett** [comment]
Looks great, though did you intended to leave the image URL set to the DLRS graph image? Maybe need a new attribute on your component for this? Also would it be ok if you made your component and page names lower case, and perhaps removed the underscores from the component attribute names (in favour of using mixed case, with leading lower case character instead). I realise probably should have some submission guidelines that state this my bad. After these tweeks,i think it will be ready to merge. Do you plan on doing a blog or other promotion on the feature? If not, no worries, i will for sure be singing its praises with full credit to yourself of course! Thanks again for such a great submission!

**Comment by wes1278** [comment]
Hey @afawcett ,

I think I've got everything you were asking for. I had a really long day so forgive me if I messed something up. :)

As far as a blog post goes, I hadn't planned anything because my blog needs a major overhaul before I start to put "good" content on it...; but I suppose it's a good idea. Feel free to announce any which way you deem fit. :) 

I'm just trying to get my dreamforce session submissions in on time. I've got some sweet stuff I hope I get to show off.

Thanks!

**Comment by wes1278** [comment]
@afawcett did you want to take another look at this?

**Comment by afawcett** [comment]
Nice looking good, can you just update the demo screenshot of the component and its all good! :+1:

**Comment by wes1278** [comment]
It is referencing where it will be. The image just isn't in your repo yet. Is github smart enough to fix the image paths during the merging of a pull request?

**Comment by afawcett** [comment]
Merged, thanks again, tweeted my thanks for this, great job!

**Comment by wes1278** [comment]
Thanks! Appreciate the merge!

**Pull request merged**
