### PR TITLE
Grace period history retention property

### PR DESCRIPTION
**Pull request by DouglasCAyers**
Added gracePeriodDays property and example of setting HistoryRetentionPolicy on a custom object. I performed this operation today and figured it's best to share!

For this change, I did create a separate branch off of my local master, unfortunately that was after I had already committed the "dependent picklists" code to my local master branch, so that change is coming along for the ride on this pull request (I figured that's ok...).

Assuming you agree to pull in each of these pull requests, and since they affect similar files, I think when merging them in you may need to rebase???? I'm not a git expert.... but I found this article.. http://stackoverflow.com/questions/16696528/how-to-submit-multiple-pull-requests-in-github-when-they-may-conflict-slightly

Thanks

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks for this, i assume these are new for Summer'15? I've yet to update the library fully for this, which normally is done as a whole. Happy to add these in the meantime though, just wanted to check they won't go away when i do refresh this class for Summer'15.

**Comment by DouglasCAyers** [comment]
I am not sure if the `gracePeriodDays` or `displayLocationInDecimal` fields are new for Summer '15. They are not listed in the [release notes](http://docs.releasenotes.salesforce.com/en-us/summer15/release-notes/rn_api_meta.htm) nor in the WSDL itself, but they are available in the SOAP response.

Until these fields are part of the WSDL then I imagine the patcher class will be necessary to add these properties to the generated `MetadataService.cls`?

**Comment by afawcett** [comment]
Thanks for these! :+1:  I've merged them, but one last request, can you update the notes in the README that describe how to create the MetadataService.cls after a new version. I use this when updating and will need a reminder to make your custom changes until the patcher or ideally WSDL is updated. Ideally add the lines in the README steps to just copy and paste.

**Comment by DouglasCAyers** [comment]
Will do! Thanks for allowing me to contribute and thanks for sharing this awesome project!

**Comment by afawcett** [comment]
No problem at all!

BTW, one theory i had was if these fields are part of some pilot / beta of some kind, do you think thats the case? Do other docs, say on the SF API object doc, suggest this might be the case?

**Comment by DouglasCAyers** [comment]
I had the same theory, but I can't find any mention that these missing fields from the WSDL are beta.

The [History Retention Policy](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_historyretentionpolicy.htm) page does not mention a pilot / beta; it has been available since API v31.

The [Custom Field](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm) page does not mention a pilot / beta either for `displayLocationInDecimal`. [Geolocation fields have been GA since Spring '15](http://releasenotes.docs.salesforce.com/en-us/spring15/release-notes/rn_forcecom_general_geolocation_ga.htm).

**Comment by afawcett** [comment]
Ok, well thanks for updating the README, i'll perhaps look at a way to enhance the patcher to allow these type of changes more easily.

**Comment by DouglasCAyers** [comment]
Do you have any special "insider contacts" at Salesforce you could ping about it or do we have to just open normal support cases?

**Comment by afawcett** [comment]
Yeah let me ping someone....

**Pull request merged**
