### PR TITLE
adding support for RestrictedPicklist

### LINKED ISSUE #106: apex Type Not found
I'am trying to access the information about an object, i keep getting the following exception:
<b>Web service callout failed: Unable to parse callout response. Apex type not found for element restrictedPicklist</b>

I have no idea what i am missing in the mdapi class .

### PR DESCRIPTION
**Pull request by grigri9**
I added the metadata properties for RestrictedPicklist metadata to fix the apex type not found exception. 

> Web service callout failed: Unable to parse callout response. Apex type not found for element restrictedPicklist

Closes #106

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks for this. Would you mind add a note to the steps in the README, to remind me or a future dev refreshing the wrapper to add the boolean to the WSDL before generating the Apex class. Otherwise next time i or someone else refreshes it for a new release this edit will stand a chance of getting lost. You should see another example of this in the steps already.

**Comment by grigri9** [comment]
Sure, you mean just add it to the "Known Issues and Resolutions" section in the readme.md?

**Comment by afawcett** [comment]
Yep, into [this section](https://github.com/financialforcedev/apex-mdapi#how-to-create-your-own-metadataservicecls).

**Comment by Blackbaud-CraigPemberton** [comment]
@afawcett This appears to be present in master. Could we close this issue?

**Pull request closed without merging**
